// vue/src/views/PhoneBookEdit.vue
<template>
  <div class="page">
    <h1>{{ id ? 'Редактировать контакт' : 'Новый контакт' }}</h1>
    <p v-if="loading">Загрузка...</p>
    <PhoneBookForm v-else :record="record" @save="handleSave" @cancel="handleCancel" />
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { usePhoneBookRecord } from '@/composables/usePhoneBook';
import PhoneBookForm from '@/components/PhoneBookForm.vue';
import type { PhoneBookRecord } from '@/types';

const route = useRoute();
const router = useRouter();
const { record, loading, load, save } = usePhoneBookRecord();

const id = route.params.id ? Number(route.params.id) : null;

onMounted(async () => {
  if (id) {
    await load(id);
  }
});

const handleSave = async (data: PhoneBookRecord) => {
  await save(data);

  router.push({ name: 'list' });
};

const handleCancel = () => {
  router.push({ name: 'list' });
};
</script>

// react/src/pages/PhoneBookEdit.tsx
import { useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { usePhoneBookRecord } from '../hooks/usePhoneBookRecord';
import PhoneBookForm from '../components/PhoneBookForm';
import type { PhoneBookRecord } from '../types';

export default function PhoneBookEdit() {
  const { id: idParam } = useParams();
  const navigate = useNavigate();
  const { record, loading, load, save } = usePhoneBookRecord();

  const id = idParam ? Number(idParam) : null;

  useEffect(() => {
    if (id) {
      load(id);
    }
  }, [id, load]);

  const handleSave = async (data: PhoneBookRecord) => {
    await save(data);
    navigate('/');
  };

  const handleCancel = () => {
    navigate('/');
  };

  return (
    <div className="page">
      <h1>{id ? 'Редактировать контакт' : 'Новый контакт'}</h1>
      {loading && <p>Загрузка...</p>}
      {!loading && (
        <PhoneBookForm record={record} onSave={handleSave} onCancel={handleCancel} />
      )}
    </div>
  );
}
